### ISSUE TITLE
how it work?

### ISSUE THREAD

**Issue by huangyanxiong01** [socketio/socket.io-emitter#60]
#### Redis is required？
```shell
Error: Redis connection to 127.0.0.1:12345 failed - connect ECONNREFUSED 127.0.0.1:12345
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:14)
```
The `127.0.0.1:12345` is socket.io listen port
#### Why require Redis?

**Comment by darrachequesne** [comment]
`socket.io-emitter` allow you to broadcast packets to other `socket.io` servers through Redis pub/sub mechanism.

``` 
emitter -----> Redis |----> server |----> client
                     |             |----> client
                     |             | ...
                     |----> server |----> client
                                   |----> client
                                   | ...
```

**Comment by huangyanxiong01** [comment]
3q
